apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whatnot-api-ingress
  namespace: whatnot-api
  # annotations:
  #   kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whatnot-api-svc
                port:
                  number: 80
